config/routes.rb
Rails.application.routes.draw do
  get 'calendar', to: 'calendar#index'
  devise_for :users, module: :user
  get '/', to: 'dashboard#index', as: 'dashboard'
  get '/profile', to: 'profile#index'
  put '/profile', to: 'profile#update'
  post '/role/sort', to: 'role#sort'
  resources :role, only: [:index, :show]
  get '/search', to: 'global_search#search'
  get '/google/oauth2callback', to: 'google#oauth2callback'
  get '/google/calendar', to: 'google#calendar'
  post '/tag', to: 'tag#create'
  get '/tag', to: 'tag#index'
  delete '/tag', to: 'tag#destroy'
  get '/autocomplete/views', to: 'autocomplete#views'
  get '/autocomplete/tags', to: 'autocomplete#tags'
  resources :note
  resources :web_link do
    get 'html', to: 'web_link#html'
  end
  resources :view, only: [:show, :index]
  post '/view', to: 'view#create'
  delete '/view', to: 'view#destroy'
  resources :goal
  resources :life_event
end

app/views/modal/_modal_goal.html.erb
<% new_goal = !goal.persisted? %>

<script type="template" id="<%= new_goal ? 'new-goal-template' : 'goal-template' %>">
  <div id="modal-goal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <%= t(new_goal ? :new_goal : :edit_goal) %>
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <input name="title" type="text" class="form-control" placeholder="<%= t :goal %>..." value="<%= goal.text %>">
          </div>
          <div class="row">
            <div class="col-md">
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-secondary <%= 'active' if (goal.term == 'short' || new_goal) %>">
                  <input type="radio" name="term" value="short" autocomplete="off" <%= 'checked' if (goal.term == 'short' || new_goal) %>>
                  <%= t :short_term %>
                </label>
                <label class="btn btn-secondary <%= 'active' if goal.term == 'long' %>">
                  <input type="radio" name="term" autocomplete="off" value="long" <%= 'checked' if goal.term == 'long' %>>
                  <%= t :long_term %>
                </label>
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <input type="text" name="goal_date" class="form-control datepicker-orient-bottom" data-provide="datepicker" placeholder="📅 <%= t :goal_time_frame %>..." value="<%= goal.goal_date&.strftime '%m/%d/%Y' %>">
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <% view = goal.views.first %>
                <select name="view" class="form-control selectize">
                  <option selected disabled data-placeholder="true"><%= t :select_view %>...</option>
                  <% RoleCategory.all.find_each do |role_category| %>
                    <option value="<%= role_category.id %>" <%= 'selected' if view&.label == role_category.id %>><%= role_category.short_name %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <% tags = goal.tags.map(&:label).join ' ' %>
            <input class="selectize" type="text" name="tags" value="<%= tags %>">
          </div>
          <div class="form-group">
            <textarea class="form-control" name="description">
              <%= goal.description %>
            </textarea>
          </div>
        </div>
        <div class="modal-footer">
          <% unless new_goal %>
            <button type="button" class="btn btn-danger delete">
              <%= t :Delete %>
            </button>
          <% end %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <%= t :close %>
          </button>
          <button type="button" class="btn btn-primary" name="save"><%= t :save %></button>
        </div>
      </div>
    </div>
  </div>
</script>

<div id="delete-goal-modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div><strong>Are you sure you want to delete this goal?</strong></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger confirm">Yes, Delete</button>
      </div>
    </div>
  </div>
</div>

<div id="goal-modal-content"></div>

<%= content_for :footer do %>
  <script>
    function initGoalModal(id) {
      const $goalTemplate = $(id ? '#goal-template' : '#new-goal-template');
      const $goalModalContent = $('#goal-modal-content');
      $goalModalContent.html($goalTemplate.html());

      const $goalModal = $('#modal-goal');
      const $goalTitle = $('#modal-goal input[name=title]');
      // const $goalTerm = $('#modal-goal input[name=term]');
      const $goalDate = $('#modal-goal input[name=goal_date]');
      const $goalView = $('#modal-goal select[name=view]');
      const $goalTags = $('#modal-goal input[name=tags]');
      const $goalDescription = $('#modal-goal textarea[name=description]');
      const $saveButton = $('#modal-goal button[name=save]');
      const $goalDelete = $goalModalContent.find('button.delete');
      const $deleteModal = $('#delete-goal-modal');


      $goalDate.fullCalendar({
        header: { center: 'month,year' },
        views: {
          month: {
            titleFormat: 'MM/DD/YYYY'
          }
        }
      });

      $goalTags.selectize({
        delimiter: ' ',
        loadThrottle: 100,
        valueField: 'label',
        labelField: 'label',
        searchField: 'label',
        createOnBlur: true,
        create: true,
        placeholder: '<%= t :tags %>...',
        load: (query, callback) => {
          if (!query.length) return callback();
          $.ajax({
            url: `<%= autocomplete_tags_path %>?q=${encodeURIComponent(query)}`,
            method: 'GET',
            error: () => {
              console.error('selectize error!');
              callback();
            },
            success: res => {
              console.log(res);
              callback(res);
            }
          });
        }
      });

      $goalDescription.summernote({
        height: 200,
        width: '100%',
        toolbar: [['style', ['bold', 'italic', 'underline', 'clear']],
          ['font', ['strikethrough', 'superscript', 'subscript']],
          ['fontsize', ['fontsize']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['height', ['height']]]
      });

      $goalModal.on('show.bs.modal', () => {
        setTimeout(() => { $goalTitle.focus(); }, 500);
      });

      id = id || '';
      const url = `<%= goal_index_path %>/${id}`;
      const method = id ? 'PUT' : 'POST';

      $saveButton.click(function () {
        ajax({
          url: url,
          method: method,
          dataType: 'json',
          data: {
            title: $goalTitle.val(),
            term: $('#modal-goal input[name=term]:checked').val(),
            goal_date: $goalDate.val(),
            tags: $goalTags.val(),
            view: $goalView.val(),
            description: $goalDescription.val()
          },
          success: () => {
            location.reload();
          },
          error: err => {
            console.error(err);
          }
        });
      });

      $goalDelete.click(function() {
        $deleteModal.modal('show');
        $deleteModal.find('button.confirm').click(() => {
          ajax({
            url: url,
            method: 'DELETE',
            success: data => {
              console.log(data);
              location.reload();
            },
            error: alert
          });
        });
      });
    }
  </script>
<% end %>

app/views/modal/_modal_life_event.html.erb
<% new_event = !life_event.persisted? %>

<script type="template" id="<%= new_event ? 'new-life-event-modal-template' : 'life-event-modal-template' %>">
  <div id="modal-life-event" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <%= t(new_event ? :new_life_event : :edit_life_event) %>
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <input type="text" name="title" class="form-control" placeholder="<%= t :life_event %>..." value="<%= life_event.title %>">
          </div>
          <div class="form-group">
            <% url = life_event.web_links.first&.url %>
            <input type="text" name="url" class="form-control" placeholder="<%= t :url %>..." value="<%= url %>">
          </div>
          <div class="row">
            <div class="col-md">
              <div class="form-group">
                <input type="text" name="from_date" class="form-control datepicker-orient-bottom" data-provide="datepicker" placeholder="<%= t :from %>..." value="<%= life_event.from_date&.strftime('%m/%d/%Y') %>">
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <input type="text" name="to_date" class="form-control datepicker-orient-bottom" data-provide="datepicker" placeholder="<%= t :to %>..." value="<%= life_event.to_date&.strftime('%m/%d/%Y') %>">
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <% views = life_event.views.all.order(:created_at) %>
                <% primary_view = views[0] %>
                <select name="view" class="form-control">
                  <option selected disabled data-placeholder="true"><%= t :view %>...</option>
                  <% RoleCategory.all.find_each do |role_category| %>
                    <option value="<%= role_category.id %>" <%= 'selected' if primary_view&.label == role_category.id %>><%= role_category.short_name %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <% secondary_view = views[1] %>
                <select name="secondary_view" class="form-control">
                  <option selected disabled data-placeholder="true"><%= t :secondary_view %>...</option>
                  <% RoleCategory.all.find_each do |role_category| %>
                    <option value="<%= role_category.id %>" <%= 'selected' if secondary_view&.label == role_category.id %>><%= role_category.short_name %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div>
              <input type="checkbox" name="prototype" id="prototype-checkbox" <%= 'checked' if life_event.prototype? %>>
              <label for="prototype-checkbox"><%= t(:prototype) %></label>
            </div>
            <div>
              <input type="checkbox" name="show_in_annual_view" id="show-in-annual-view-checkbox" <%= 'checked' if life_event.show_in_annual_view? %>>
              <label for="show-in-annual-view-checkbox"><%= t(:show_in_annual_view) %></label>
            </div>
          </div>
          <div class="form-group">
            <textarea name="description" class="form-control">
              <%= life_event.description %>
            </textarea>
          </div>
        </div>
        <div class="modal-footer">
          <% unless new_event %>
            <button type="button" class="btn btn-danger delete">
              <%= t :Delete %>
            </button>
          <% end %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <%= t :close %>
          </button>
          <button type="button" class="btn btn-primary" name="save"><%= t :save %></button>
        </div>
      </div>
    </div>
  </div>
</script>

<div id="delete-life-event-modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div><strong>Are you sure you want to delete this life event?</strong></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger confirm">Yes, Delete</button>
      </div>
    </div>
  </div>
</div>

<div id="life-event-modal-content"></div>

<%#= content_for :footer do %>
  <script>
    function initLifeEventModal(id) {
      const calendarOptions = {
        header: { center: 'month,year' },
        views: { month: { titleFormat: 'MM/DD/YYYY' } }
      };

      const $lifeEventModalTemplate = $(id ? '#life-event-modal-template' : '#new-life-event-modal-template');
      const $lifeEventContent = $('#life-event-modal-content');
      $lifeEventContent.html($lifeEventModalTemplate.html());

      const $lifeEventModal = $('#modal-life-event');
      const $title = $('#modal-life-event input[name=title]');
      const $url = $('#modal-life-event input[name=url]');
      const $fromDate = $('#modal-life-event input[name=from_date]');
      const $toDate = $('#modal-life-event input[name=to_date]');
      const $view = $('#modal-life-event select[name=view]');
      const $secondaryView = $('#modal-life-event select[name=secondary_view]');
      const $prototype = $('#modal-life-event input[name=prototype]');
      const $showInAnnualView = $('#modal-life-event input[name=show_in_annual_view]');
      const $description = $('#modal-life-event textarea[name=description]');
      const $save = $('#modal-life-event button[name=save]');
      const $lifeEventDelete = $lifeEventModal.find('button.delete');
      const $deleteModal = $('#delete-life-event-modal');

      $fromDate.fullCalendar(calendarOptions);
      $toDate.fullCalendar(calendarOptions);

      $description.summernote({
        height: 200,
        width: '100%',
        toolbar: [['style', ['bold', 'italic', 'underline', 'clear']],
          ['font', ['strikethrough', 'superscript', 'subscript']],
          ['fontsize', ['fontsize']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['height', ['height']]]
      });

      // $lifeEventModal.on('show.bs.modal', () => {
      //   setTimeout(() => { $title.focus(); }, 500);
      // });

      id = id || '';
      const url = `<%= life_event_index_path %>/${id}`;
      const method = id ? 'PUT' : 'POST';

      $lifeEventDelete.click(function() {
        $deleteModal.modal('show');
        $deleteModal.find('button.confirm').click(() => {
          ajax({
            url: url,
            method: 'DELETE',
            success: data => {
              console.log(data);
              location.reload();
            },
            error: alert
          });
        });
      });

      $save.click(function() {
        $save.attr('disabled', true);
        ajax({
          url: url,
          method: method,
          dataType: 'json',
          data: {
            title: $title.val(),
            from_date: $fromDate.val(),
            to_date: $toDate.val(),
            view: $view.val(),
            secondary_view: $secondaryView.val(),
            description: $description.val(),
            url: $url.val(),
            prototype: $prototype.is(':checked'),
            show_in_annual_view: $showInAnnualView.is(':checked')
          },
          success: event => {
            location.reload();
          },
          error: err => {
            console.error(err);
            $save.attr('disabled', false);
          }
        });
      });
    }
  </script>
<%# end %>

app/views/modal/_modal_note.html.erb
<% new_note = !note.persisted? %>

<script type="template" id="<%= new_note ? 'new-note-template' : 'note-template' %>">
  <div id="modal-note" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <%= t(new_note ? :new_note : :edit_note) %>
          </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <input class="form-control" type="text" name="title" id="note-title" placeholder="<%= t :title %>..." value="<%= note.title %>">
          </div>
          <div class="row">
            <div class="col-md">
              <div class="form-group">
                <% views = note.views.all.order(:created_at) %>
                <% primary_view = views[0] %>
                <select id="primary-view-select" name="primary_view" class="form-control selectize">
                  <option selected disabled data-placeholder="true"><%= t :primary_view %>...</option>
                  <% RoleCategory.all.find_each do |role_category| %>
                    <option value="<%= role_category.id %>" <%= 'selected' if primary_view && primary_view.label == role_category.id %>><%= role_category.short_name %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <% secondary_view = views[1] %>
                <select id="secondary-view-select" name="secondary_view" class="form-control selectize">
                  <option selected disabled data-placeholder="true"><%= t :secondary_view %>...</option>
                  <% RoleCategory.all.find_each do |role_category| %>
                    <option value="<%= role_category.id %>" <%= 'selected' if secondary_view && secondary_view.label == role_category.id %>><%= role_category.short_name %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <select class="form-control" name="note_type" id="note-type">
                  <option selected disabled data-placholder="true"><%= t :note_type %>...</option>
                  <% Note::TYPES.each do |note_type| %>
                    <option value="<%= note_type %>" <%= 'selected' if note.note_type == note_type %>><%= note_type %></option>
                  <% end %>
                </select>
              </div>
            </div>
            <div class="col-md">
              <div class="form-group">
                <% note_learning_type = note.learning_types.first %>
                <select class="form-control" name="learning_type" id="learning-type">
                  <option selected disabled data-placholder="true"><%= t :learning_type %>...</option>
                  <% LearningType::TYPES.each do |learning_type| %>
                    <option value="<%= learning_type %>" <%= 'selected' if note_learning_type && note_learning_type.label == learning_type %>><%= learning_type %></option>
                  <% end %>
                </select>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="form-group">
              <% tags = note.tags.map(&:label).join ' ' %>
              <input id="note-tags" class="selectize" type="text" name="tags" value="<%= tags %>">
            </div>
          </div>
<!--          <div class="form-group">-->
<!--            <label for="note-views"><%#= t :urls %></label>-->
<!--            <input class="selectize" type="text" name="urls" id="note-urls">-->
<!--          </div>-->
          <div class="form-group">
<!--            <label for="note-content"><%#= t :content %></label>-->
<!--            <div>-->
<!--              <a class="toggle-controls" href="#">Toggle Controls</a>-->
<!--            </div>-->
            <textarea id="note-content" class="form-control">
              <%= note.text %>
            </textarea>
          </div>
        </div>
        <div class="modal-footer">
          <% unless new_note %>
            <button type="button" class="btn btn-danger delete">
              <%= t :Delete %>
            </button>
          <% end %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <%= t :close %>
          </button>
          <button id="note-submit" type="button" class="btn btn-primary">
            <%= t :save %>
          </button>
        </div>
      </div>
    </div>
  </div>
</script>

<div id="delete-note-modal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div><strong>Are you sure you want to delete this note?</strong></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger confirm">Yes, Delete</button>
      </div>
    </div>
  </div>
</div>

<div id="note-modal-content"></div>

<%#= content_for :footer do %>
  <script>
    function initNoteModal(id) {
      const $noteTemplate = $(id ? '#note-template' : '#new-note-template');
      const $noteModalContent = $('#note-modal-content');
      $noteModalContent.html($noteTemplate.html());

      const $note = $('#note-content');
      const $primaryView = $('#primary-view-select');
      const $secondaryView = $('#secondary-view-select');
      const $noteType = $('#note-type');
      const $noteTags = $('#note-tags');
      const $noteModal = $('#modal-note');
      const $noteTitle = $('#note-title');
      const $noteSubmit = $('#note-submit');
      const $noteDelete = $noteModalContent.find('button.delete');
      const $deleteModal = $('#delete-note-modal');
      const $learningType = $('#learning-type');
      const csrfToken = $('meta[name="csrf-token"]').attr('content');

      id = id || '';
      const url = `<%= note_index_path %>/${id}`;

      $noteDelete.click(function() {
          $deleteModal.modal('show');
          $deleteModal.find('button.confirm').click(() => {
            ajax({
              url: url,
              method: 'DELETE',
              success: data => {
                console.log(data);
                location.reload();
              },
              error: alert
            });
          });
      });

      const method = id ? 'PUT' : 'POST';

      $noteSubmit.click(() => {
        $noteSubmit.attr('disabled', true);
        $.ajax({
          url: url,
          method: method,
          beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', csrfToken)},
          dataType: 'json',
          data: {
            title: $noteTitle.val(),
            view: $primaryView.val(),
            tags: $noteTags.val(),
            note: $note.val(),
            primary_view: $primaryView.val(),
            secondary_view: $secondaryView.val(),
            note_type: $noteType.val(),
            learning_type: $learningType.val()
          },
          success: () => {
            location.reload();
          },
          error: err => {
            console.error(`submit error: ${JSON.stringify(err)}`);
          }
        });
      });

      $noteModal.on('show.bs.modal', () => {
        setTimeout(() => { $noteTitle.focus(); }, 500);
      });

      $noteTags.selectize({
        delimiter: ' ',
        loadThrottle: 100,
        valueField: 'label',
        labelField: 'label',
        searchField: 'label',
        createOnBlur: true,
        create: true,
        placeholder: '<%= t :tags %>...',
        load: (query, callback) => {
          if (!query.length) return callback();
          $.ajax({
            url: `<%= autocomplete_tags_path %>?q=${encodeURIComponent(query)}`,
            method: 'GET',
            error: () => {
              console.error('selectize error!');
              callback();
            },
            success: res => {
              console.log(res);
              callback(res);
            }
          });
        }
      });

      $note.summernote({
        height: 200,
        width: '100%',
        toolbar: [['style', ['bold', 'italic', 'underline', 'clear']],
          ['font', ['strikethrough', 'superscript', 'subscript']],
          ['fontsize', ['fontsize']],
          ['color', ['color']],
          ['para', ['ul', 'ol', 'paragraph']],
          ['height', ['height']]]
      });
    }
  </script>
<%# end %>

app/views/modal/_modal_web_link.html.erb
<script type="template" id="web-link-template">
  <%= form_tag controller: :web_link, action: :create do %>
  <div id="modal-web-link" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title"><%= t :new_link %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <input type="text" name="url" class="form-control" id="web-link-url">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">
            <%= t :close %>
          </button>
          <input type="submit" class="btn btn-primary" value="<%= t :save %>">
        </div>
      </div>
    </div>
  </div>
  <% end %>
</script>

<div id="web-link-modal"></div>

<%= content_for :footer do %>
  <script>
    $(() => {
      function initWebLinkModal() {
        const $webLinkTemplate = $('#web-link-template');
        const $webLinkModal = $('#web-link-modal');
        $webLinkModal.html($webLinkTemplate.html());
        const $webLinkUrl = $webLinkModal.find('#web-link-url');

        $webLinkModal.find('form').on('submit', () => {
          $webLinkModal.find('input[type=submit]').attr('disabled', true);
        });

        $webLinkModal.on('show.bs.modal', () => {
          setTimeout(() => $webLinkUrl.focus(), 500);
        });
      }

      initWebLinkModal();
    });
  </script>
<% end %>

app/views/modal/_modals.html.erb
<div id="modals">
  <%= render partial: 'modal/modal_goal', locals: { goal: Goal.new } %>
  <%= render partial: 'modal/modal_life_event', locals: { life_event: LifeEvent.new } %>
  <%= render partial: 'modal/modal_note', locals: { note: Note.new } %>
  <%= render 'modal/modal_web_link' %>
  <div id="modal-goal-edit"></div>
  <div id="modal-life-event-edit"></div>
  <div id="modal-note-edit"></div>
</div>