config/routes.rb
Rails.application.routes.draw do
  get 'calendar', to: 'calendar#index'
  devise_for :users, module: :user
  get '/', to: 'dashboard#index', as: 'dashboard'
  get '/profile', to: 'profile#index'
  put '/profile', to: 'profile#update'
  post '/role/sort', to: 'role#sort'
  resources :role, only: [:index, :show]
  get '/search', to: 'global_search#search'
  get '/google/oauth2callback', to: 'google#oauth2callback'
  get '/google/calendar', to: 'google#calendar'
  post '/tag', to: 'tag#create'
  get '/tag', to: 'tag#index'
  delete '/tag', to: 'tag#destroy'
  get '/autocomplete/views', to: 'autocomplete#views'
  get '/autocomplete/tags', to: 'autocomplete#tags'
  resources :note
  resources :web_link do
    get 'html', to: 'web_link#html'
  end
  resources :view, only: [:show, :index]
  post '/view', to: 'view#create'
  delete '/view', to: 'view#destroy'
  resources :goal
  resources :life_event
end

app/views/shared/_agenda.html.erb
<div id="calendar"></div>

<% content_for :footer do %>
  <script>
    $(() => {
      const $calendar = $('#calendar');

      $calendar.fullCalendar({
        defaultView: 'agendaDay',
        events: <%= @events_today.to_json.html_safe %>
      });
    });
  </script>
<% end %>

app/views/shared/_annual_view.html.erb
<div id="annual-view">
  <div class="hide-lt-768">
<!--    <div class="row">-->
      <%# (1..10).each do |num| %>
<!--        <div class="col-md text-center"><%#= num %></div>-->
      <%# end %>
<!--    </div>-->
    <% @annual_dates.each_with_index do |row, num| %>
      <div class="row">
        <% row.each do |date| %>
          <a href="<%= url_for controller: :calendar, view: 'listYear', year: date.year %>" class="year col-md" data-year="<%= date.year %>">
            <% if @life_events && @life_events[date.year].present? %>
              <% life_event = @life_events[date.year].last %>
              <% link = life_event.web_links.last %>
              <% if link %>
                <div class="heading">
                  <%= date.strftime '%Y' %> - Age
                  <%= date.year - current_user.date_of_birth.year %>
                </div>
                <div class="content">
                  <img src="data:<%= link.favicon.content_type %>;base64, <%= link.favicon.base64 %>" />
                </div>
              <% end %>
            <% else %>
              <div class="heading <%= 'today' if @today.year == date.year %>">
                <%= date.strftime '%Y' %> - Age
                <%= date.year - current_user.date_of_birth.year %>
              </div>
            <% end %>

            <% if @today.year == date.year %>
              <div class="content">
                <i class="ti-location-pin"></i>
                <%= t :you_are_here %>
              </div>
            <% end %>
          </a>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="show-lt-768">
    <%= render partial: 'shared/small_calendar' %>
  </div>
</div>

<script type="template" id="year-popover-template">
  <div>
    <strong><%= t :life_events %></strong>
    <ul>
    {{ _.each(lifeEvents, lifeEvent => { }}
      <li><a class="life-event" href="javascript:editLifeEventModal({{= lifeEvent.id}})">{{= lifeEvent.title }}</a></li>
    {{ }); }}
    </ul>
  </div>
</script>

<% if @life_events %>
  <%= content_for :footer do %>
    <script>
      $(() => {
        _.templateSettings = {
          interpolate: /\{\{=(.+?)\}\}/g,
          evaluate: /\{\{(.+?)\}\}/g
        };

        const $years = $('a.year');
        // noinspection JSAnnotator
        const lifeEvents = <%= @life_events.to_json.to_s.html_safe %>;
        const popoverTemplate = _.template($('#year-popover-template').html());
        const yearOnHoverIn = function () {
          const year = $(this).data('year');
          const yearLifeEvents = lifeEvents[year];
          if (yearLifeEvents.length > 0) {
            const $popoverContent = $(popoverTemplate({ lifeEvents: yearLifeEvents }));
            const showPopover = () => $(this).popover({
              title: year,
              content: $popoverContent,
              html: true,
              placement: 'top',
              trigger: 'focus'
            }).popover('show');

            let popover = showPopover();

            $popoverContent.hover(() => {
              popover = showPopover();
            }, () => popover.popover('hide'));
          }
        };
        const yearOnHoverOut = function () {
          $(this).popover('hide');
        };

        $years.hover(yearOnHoverIn, yearOnHoverOut);
      });
    </script>
  <% end %>
<% end %>

app/views/shared/_calendar.html.erb
<div id="calendar"></div>

<% content_for :footer do %>
  <script>
    $(() => {
      const $calendar = $('#calendar');

      $calendar.fullCalendar({
        defaultView: '<%= @calendar[:view] %>',
        defaultDate: moment().set({
            year: <%= @calendar[:date].year %>,
            month: <%= @calendar[:date].month - 1 %>,
            date: <%= @calendar[:date].day %>
        }),
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'month,listWeek,listYear'
        },
        eventClick: function (e) {
          window.open(e.url, '_blank');
          return false;
        },
        events: <%= @calendar[:events].to_json.html_safe %>
      });
    });
  </script>
<% end %>

app/views/shared/_edit_button.html.erb
<a href="#" class="edit-button" data-type="<%= type %>" data-id="<%= id %>">
  <i class="fa fa-edit"></i>
</a>

app/views/shared/_role_category_sortable.html.erb
<ul id="role-category-sortable">
  <%# RoleCategory.all.each do |role_category| %>
  <% current_user.role_categories.order(importance: :desc).each do |role_category| %>
    <li data-label="<%= role_category.label %>">
      <span class="importance">
        <%= role_category.importance %>
      </span>
      :: <%= role_category.short_name %></li>
  <% end %>
</ul>

<%= content_for :footer do %>
  <script>
    $(() => {
      const $roleCategory = $('#role-category-sortable');

      $roleCategory.sortable();
      $roleCategory.disableSelection();

      $roleCategory.on('sortstop', () => {
        const $items = $roleCategory.find('li');

        let i = $items.length;
        $items.each(function() {
          $(this).find('.importance').text(`${i--}`);
        });

        ajax({
          url: '<%= role_sort_path %>',
          method: 'POST',
          dataType: 'json',
          data: { role_categories: $.map($items, i => $(i).data('label')) },
          success: console.log,
          error: console.error
        });
      });
    });
  </script>
<% end %>

app/views/shared/_roles_and_goals.html.erb
<!--<div id="goals">-->
    <%# @role_categories.each do |role_category| %>
<!--    <div class="row">-->
<!--      <div class="flex-md-column flex-md-nowrap">-->
<!--        <div class="role-category">-->
<!--          <a href="<%#= view_path role_category.label %>">-->
<!--            <span class="icon-holder">-->
<!--              <i class="<%#= role_category.icon_class %>"></i>-->
<!--            </span>-->
            <%#= role_category.short_name %>
<!--          </a>-->
<!--        </div>-->
<!--      </div>-->
<!--      <div class="flex-md-column">-->
        <%# role_category.goals.map(&:text).each do |goal| %>
<!--          <span class="label label-default"><%#= goal %></span>-->
        <%# end %>
<!--      </div>-->
<!--    </div>-->
    <%# end %>
<!--</div>-->

<%= render partial: 'shared/role_category_sortable' %>

app/views/shared/_small_calendar.html.erb
<div class="small-calendar"  data-date="<%= Date.today.strftime '%m-%d-%Y' %>" data-provide="datepicker-inline">
</div>

<%= content_for :footer do %>
  <script>
    $('.calendar').datepicker();
  </script>
<% end %>

app/views/shared/_time_spent.html.erb
<div id="time-spent">
  <canvas id="time-spent-chart"></canvas>
  <% if @time_quote %>
    <div class="quote time-quote">
      <i class="fa fa-quote-left"></i>
      <span><%= @time_quote %></span>
      <i class="fa fa-quote-right"></i>
    </div>
  <% end %>
</div>

<% content_for :footer do %>
  <script>
    $(() => {
      const $time_spent_chart = $('#time-spent-chart');

      new Chart($time_spent_chart, {
        type: 'pie',
        data: {
          datasets: [{
            data: <%= @time_spent_values %>,
            backgroundColor: [
              'rgba(255, 99, 132)',
              'rgba(54, 162, 235)',
              'rgba(255, 206, 86)',
              'rgba(75, 192, 192)',
              'rgba(153, 102, 255)'
            ]
          }],
          labels: <%= @time_spent_labels.to_s.html_safe %>
        },

      });
    });
  </script>
<% end %>